name: Python Checks
on: [push]
jobs:
        python:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout Github repo
                          uses: actions/checkout@v3
                        - name: Set up python
                          uses: actions/setup-python@v4
                        - name: Install dependencies
                          run: |
                                  python -m pip install --upgrade pip
                                  python -m pip install black
                        - name: Lint with black
                          run: python3 -m black --check .
